### ISSUE TITLE
[Reopen] Info?

### ISSUE THREAD

**Issue by Callial** [freddedotme/BuildSubmission#3]
Sorry about the necro I was waiting for an email notifying me you had responded and I did not receive it due to a subscription error.

the problem I have is, you say all the info is there but you give no insight at all into how to customise anything. I want to know if any customization is in fact possible.

"Setup ranks, Setup rank permissions, is there a way to add rank names rather than numbers? is there a way to have a prefix or suffix in chat or tab?"

Thanks again for dealing with me 
~Callial(DH)

**Comment by freddedotme** [comment]
No worries, so let me explain it as good as I possibly can.

The reason why there has to be a number in the permission node is because that's how the algorithm works for checking what permission that should be picked. So if a person has both "bs.rank2" and "bs.rank3", BuildSubmission will search and find in this case the highest one which is 3.

Since BuildSubmission will execute any of the commands in the commands.yml you can simply do something like this if you want to have a specific pre/suffix:

    - '{rank1} promote {player}' 

(or whatever the command is for promoting a player using your preferred permission plugin)
This will promote the player to the next rank on your server. The prefix/suffix you want you just add as usual in your permission plugin, not in BuildSubmission.

**Comment by Callial** [comment]
So if I use PEx I would create a pex ladder and BS would promote them there?

**Comment by freddedotme** [comment]
Exactly, let me show you an example to be extra clear:

     '{rank1} pex promote <player>'
     '{rank2} pex promote <player>'
     '{rank3} pex promote <player>'

This would promote the player when he/she reaches rank 1, 2 and 3.
There is no need to use the "bs.rankN" since the rank is saved in a .yml file, that permission node is just used for specific cases.

If you need more help I'll gladly help you in game if you share an IP address.

EDIT: Remember to put the commands in either ONLINE/OFFLINE depending on if they need to be online or not when it's executed.

**Comment by Callial** [comment]
I will experiment for a while :), I am just setting up a duel server plot creative world, the main world is for all players and the other is a single massive town that only the top rank players can build in. Once I have all the other plugins configured I will worry about ranks :). It shouldn't be longer than 2 weeks tho as 3 weeks is my deadline, and I will more than likely be working on other servers on the network by then XD.

**Comment by freddedotme** [comment]
Alright, good luck with that. 👍 
If you need any further help then just create a new issue.

Closing this one now.
